### ISSUE TITLE
Export GatingSet to flowJo-compatible GatingML files

### ISSUE THREAD

**Issue by mikejiang** [RGLab/CytoML#1]

**Comment by mikejiang** [comment]
Within `flowJo v10.1` free trial version, I loaded the sample [CytoTrol_CytoTrol_1.fcs.zip](https://github.com/RGLab/CytoML/files/226967/CytoTrol_CytoTrol_1.fcs.zip) and drag and drop the `gatingML` [CytoTrol_CytoTrol_1.fcs.xml.zip] (generated from `GatingSet` by `CytoML`) (https://github.com/RGLab/CytoML/files/226973/CytoTrol_CytoTrol_1.fcs.xml.zip) 

here is the outcome
![image](https://cloud.githubusercontent.com/assets/1385649/14657997/ce22329a-0645-11e6-9a1d-fe0863900344.png)

* the gating hierarchy is correctly imported
* `trans` and `comp` were rejected
* only the first gate `not debris` is imported correctly

@ptvan mentioned that `flowJo` only takes `gatingML1.5` version of `compensation`. but I didn't find the `API` for writing `gatingML 1.5`  in `flowUtils`.  @jspidlen, do you think you still have that legacy code?

Even with the `compensation` resolved, it is not certain whether `transformation` error is related to this.

**Comment by mikejiang** [comment]
Ok, here is the answer from @ptvan 

> Hi Phu,
> 
> 1) Sorry, flowUtils cannot write Gating-ML 1.5 output
> 
> 2) There are several other important changes between Gating-ML 1.5 and Gating-ML 2.0 (as summarized in pages 91-93 of flowcyt.sf.net/gating/latest.pdf). You could change the spilloverMatrix -> spectrumMatrix (manually or by altering the source code), but the result would be far from Gating-ML 1.5. Most importantly, the way how the transformation workflow is implemented is completely different between Gating-ML 1.5 (which transforms data using compound transformation with piece explicitly specified), and Gating-ML 2.0 (which is mainly based on an implicit workflow). To be honest, FlowJo has always had a bit of trouble working with Gating-ML transforms, so even if you got a proper Gating-ML 1.5 output, FlowJo wouldn't likely reproduce the gate memberships properly. 
> 
> 3) I believe FlowJo's committed to improve their Gating-ML support, including proper support for Gating-ML 2.0 with the spectrumMatrix element (eventually). Maybe try to ping them to check what their estimated timeline may be. You can mention that Gating-ML 2.0 is now an official ISAC standard (i.e., approved by ISAC council on January 13, 2015).
> 
> Cheers,
> Josef
> 
> --
> Josef Spidlen, Ph.D.

**Comment by jspidlen** [comment]
Nice, so you found my old answer :-)
I think it still applies, but let me know if you need any more details.

Cheers,
Josef

**Comment by mikejiang** [comment]
I've tried different versions of  `gatingML` for `spilloverMatrix` 
*  `gatingML 1.5`
* `gatingML 2.0` 
* `flowJo`'s own flavor of `gatingML`

None of these works. And main obstacle is that `flowJo` is not specific about where exactly goes wrong.

**Comment by jspidlen** [comment]
Hmm... I recall FlowJo reporting (at some point in the past) that "most of"
the Gating-ML 1.5 unit tests were working for them. So you could look at
the gatingMLData BioConductor package and checkout 31TrCompensation.xml in
inst/extdata/Gating-MLFiles. Just try to drag & drop that one and see if
that works in FlowJo, and if it does, you would have an example of a
Gating-ML file with spillover matrix that FlowJo can digest...

**Comment by mikejiang** [comment]
It doesn't work either
![image](https://cloud.githubusercontent.com/assets/1385649/14689363/d7047dbc-06fb-11e6-84c4-3c3832f64cb4.png)
Maybe `flowJo` changed the `gatingML` parser ever since that report?

**Comment by jspidlen** [comment]
That's possible... you could try to talk to Jay, but I doubt that there is
an easy fix at their end.

**Comment by mikejiang** [comment]
Development on the standard GatingML output is discontinued since we've addressed #2
