### ISSUE TITLE
flowjo_to_gatingset alternatively takes h5 files as data input

### ISSUE THREAD

**Issue by mikejiang** [RGLab/CytoML#100]
Currently `flowjo_to_gatingset(ws, path)` , the path points to the FCS folder. With introducing `cytoqc` workflow, sometime FCS files needs to go through pre-cleaning process before they can be used for flowJo parsing. It makes sense to optionally allow `path` to be pointing the `h5` files which are preprocessed and written by `cytoqc` to avoid re-parsing and re-creating h5 files.

**Comment by masato-ogishi** [comment]
Sounds like a good plan! Thanks!

**Comment by mikejiang** [comment]
It took longer than expected to finally implement the support for `cytoset` as the alternative input for flowjo parser.
Here is the example
https://rpubs.com/rglab/622259
pull the latest version from master branch and let me know how it works for you

**Comment by masato-ogishi** [comment]
Thanks! But unfortunately the installation from github was not successful. For now I wrote my own workaround to avoid issues. I'll try when you update the prebuilt package in Bioconductor next time.

**Comment by jacobpwagner** [comment]
@masato-ogishi , without your installation error, it's hard to be sure, but I suspect it was just that the other RGLab packages are still at the Bioconductor 3.11 release versions so you are getting a version clash when you try to update `CytoML` to the development version, which is dependent on the development versions of  `cytolib` and `flowWorkspace`. You could try updating the relevant parts of the toolchain to the GitHub versions first:

```
remotes::install_github("RGLab/cytolib")
remotes::install_github("RGLab/flowCore")
remotes::install_github("RGLab/flowWorkspace")
remotes::install_github("RGLab/CytoML")
```

**Comment by masato-ogishi** [comment]
Thanks but it seems something is wrong on my Mac. I tried many things including the installation of Command Line Tools for XCode and gcc@8 but couldn't go through the pkgbuild process. The "pkgbuild::check_build_tools(debug = TRUE)" command ddi not work either.

remotes::install_github("RGLab/cytolib")
Downloading GitHub repo RGLab/cytolib@master
Error: Failed to install 'cytolib' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

It is not the error of RGLab packages so anyway I'll wait...

**Comment by mikejiang** [comment]
I've pushed the patch to bioc development branch. Once it(CytoML 2.1.4) is built you should be able to install the binary from it without needing to compile.

**Comment by masato-ogishi** [comment]
Now the workflow becomes much faster and more flexible for me. Thank you so much!

**Comment by mikejiang** [comment]
Glad to hear. Please go ahead to close the issue if you consider it as resolved.

**Comment by masato-ogishi** [comment]
I can't. Maybe because I'm not the person that opened this issue? Thanks.
