### ISSUE TITLE
docker version question

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/CytoML#105]
Hey @mikejiang and @jacobpwagner,

Recently updated my Bioconductor packages, and it updated my cytolib package to 2.1.7. Now when I try to use `gatingset_to_flowjo` from CytoML, I get: 

```
> gatingset_to_flowjo(gs, outFile)
Using docker image rglab/gs-to-flowjo:devel to write FlowJo workspace...
Warning message:
In gatingset_to_flowjo(gs, outFile) :
  docker image 'rglab/gs-to-flowjo:devel' is built with different cytolib version of from R package: 2.1.4 vs 2.1.7
```
I tried updating the docker using:

`docker pull rglab/gs-to-flowjo:devel`

But it says the docker is up to date, and I'm getting the same error. 

Should I be updating the docker in a different way? Or, is there a way to revert my cytolib version to 2.1.4? Thanks!

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] knitr_1.28                gridExtra_2.3             colorRamps_2.3           
 [4] scales_1.1.1              cytolib_2.1.7             CytoML_2.1.6             
 [7] tibble_3.0.1              data.table_1.12.8         ggcyto_1.17.0            
[10] ggplot2_3.3.2             ncdfFlow_2.35.1           BH_1.72.0-3              
[13] RcppArmadillo_0.9.900.1.0 flowCore_2.1.0            flowWorkspace_4.1.4      
[16] openCyto_2.1.0      

```

**Comment by jacobpwagner** [comment]
Hey @alexheubeck . Sorry about that. I still need to add a hook to the docker build for `gs-to-flowjo:devel` to make it run every time `cytolib` is updated. For now I forced a manual build so it should hopefully be ready soon. Either way, I'm going to leave this issue open as a reminder for myself and I'll also let you know as soon as the `cytolib 2.1.7`-built image is available.

**Comment by jacobpwagner** [comment]
@alexheubeck , try again now after a fresh pull:
```
docker pull rglab/gs-to-flowjo:devel
```
Let me know if you still run in to any issues.

**Comment by alexheubeck** [comment]
That worked, thanks!

**Comment by jacobpwagner** [comment]
I added the hook and it seems to be working, so hopefully updates to `cytolib` will keep the `gs-to-flowjo` image up-to-date as well moving forward.
