### ISSUE TITLE
Problems with CytoML package

### ISSUE THREAD

**Issue by Chrissi92** [RGLab/CytoML#114]
Hello together, 
I would like to evaluate my Flowjo data in R, and so I came across the CytoML package.

However, I have some troubles with it. I tried to install the packages and load the libraries, but I  am always getting error messages, even when I try different options.

It would be so great if you could check the code and if you would have any suggestions. 

Thank you very much in advance. 

Best, 
Christina

### Option1:

> if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
> 
> BiocManager::install("CytoML")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'CytoML'
package �CytoML� is in use and will not be installedInstallation path not writeable, unable to update packages: MASS, mgcv, nlme, survival
Old packages: 'glue'
Update all/some/none? [a/s/n]: 
a
cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'versuche URL 'https://cran.biodisk.org/bin/windows/contrib/4.0/glue_1.4.2.zip'
Content type 'application/zip' length 155551 bytes (151 KB)
downloaded 151 KB

package ‘glue’ successfully unpacked and MD5 sums checked
cannot remove prior installation of package �glue�Problem C:\R-4.0.2\R_LIBS_USER\00LOCK\glue\libs\x64\glue.dll nach C:\R-4.0.2\R_LIBS_USER\glue\libs\x64\glue.dll zu kopieren: Permission deniedrestored �glue�
The downloaded binary packages are in
	C:\Users\aulehner\AppData\Local\Temp\Rtmpmg0ZoC\downloaded_packages
> 
> if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
> 
> BiocManager::install("flowWorkspace")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'flowWorkspace'
cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'versuche URL 'https://bioconductor.org/packages/3.11/bioc/bin/windows/contrib/4.0/flowWorkspace_4.0.6.zip'
Content type 'application/zip' length 8455899 bytes (8.1 MB)
downloaded 8.1 MB

package ‘flowWorkspace’ successfully unpacked and MD5 sums checked
cannot remove prior installation of package �flowWorkspace�Problem C:\R-4.0.2\R_LIBS_USER\00LOCK\flowWorkspace\libs\x64\flowWorkspace.dll nach C:\R-4.0.2\R_LIBS_USER\flowWorkspace\libs\x64\flowWorkspace.dll zu kopieren: Permission deniedrestored �flowWorkspace�
The downloaded binary packages are in
	C:\Users\aulehner\AppData\Local\Temp\Rtmpmg0ZoC\downloaded_packages
Installation path not writeable, unable to update packages: MASS, mgcv, nlme, survival
Old packages: 'glue'
Update all/some/none? [a/s/n]: 
a
cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'versuche URL 'https://cran.biodisk.org/bin/windows/contrib/4.0/glue_1.4.2.zip'
Content type 'application/zip' length 155551 bytes (151 KB)
downloaded 151 KB

package ‘glue’ successfully unpacked and MD5 sums checked
cannot remove prior installation of package �glue�Problem C:\R-4.0.2\R_LIBS_USER\00LOCK\glue\libs\x64\glue.dll nach C:\R-4.0.2\R_LIBS_USER\glue\libs\x64\glue.dll zu kopieren: Permission deniedrestored �glue�
The downloaded binary packages are in
	C:\Users\aulehner\AppData\Local\Temp\Rtmpmg0ZoC\downloaded_packages
> library(CytoML)
> library(flowWorkspace)
As part of improvements to flowWorkspace, some behavior of
GatingSet objects has changed. For details, please read the section
titled "The cytoframe and cytoset classes" in the package vignette:

  vignette("flowWorkspace-Introduction", "flowWorkspace")
> manual_gating_xml = system.file("extdata", 
+                                 package = "flowWorkspaceData",
+                                 "manual.xml")
> ws = openWorkspace(manual_gating_xml)
Fehler: openWorkspace is now deprecated by CytoML::open_flowjo_xml. Please library(CytoML) first!

### Option 2:
> install_conditional <-function(pkg, source = c("Bioc", "CRAN", "RGLab")) {
+   source <- match.arg (source, c("Bioc", "CRAN", "RGLab"))
+   utils::chooseCRANmirror(ind = 64)
+   for (p in kg) {
+     if ( source == "CRAN") {
+       if (is.na(match(p, installed.packages()[, "Package"]))) {
+         install.packages(p, ask = FALSE)
+       } else {
+         update.packages(p)
+       }
+     } else if (source == "Bioc") {
+         BiocManager::install(p, ask = FALSE, update = FALSE, type = "source")
+       
+     } else {
+         devtools::install_github(paste("RGLab", p, sep = "/"), ref = "trunk")
+       }
+ }
+ }
> install_conditional(
+   c(
+     "MLmetrics",
+     "webshot",
+     "Gmisc",
+     "rsvg",
+     "DiagrammeR",
+     "DiagrammeRsvg",
+     "BiocManager",
+     "devtools",
+     "cowplot", 
+     "png",
+     "grid",
+     "gridExtra",
+     "gtable"
+   ),
+   source = "CRAN"
+ )
Fehler in install_conditional(c("MLmetrics", "webshot", "Gmisc", "rsvg",  : 
  Objekt 'kg' nicht gefunden
> devtools::install_github("RGLab/cytolib@v2.0.3")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/RProtoBufLib@v1.3.7")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/flowCore@v1.3.2")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/flowWorkspace@v3.29.7")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/openCyto@v1.19.2")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/CytoML@v1.7.10")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/CytoML@v1.7.10")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> devtools::install_github("RGLab/ggcyto@v1.9.12")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum
> library(CytoML)
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table     
Fehler: package or namespace load failed for ‘CytoML’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 Namensraum ‘cytolib’ 1.3.2 ist geladen, aber >= 2.0.3 wird benötigt
> devtools::install_github("RGLab/CytoML@v2.0.3")
Fehler: .onLoad in loadNamespace() für 'pkgload' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: Paket ‘backports’ hat keinen Namensraum

**Comment by gfinak** [comment]
Your first error:
```
Installing package(s) 'CytoML'
package �CytoML� is in use and will not be installed Installation path not writeable, unable to update packages: MASS, mgcv, nlme, survival
```
suggests (amongst other things) that you don't have write permission to update your system.

Your next error:

```
cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL
```
suggests your system is somehow misconfigured. 
The URL to the `PACKAGES.rds` file should look like:
`https://bioconductor.org/packages/3.11/bioc/bin/windows/contrib/4.0/PACKAGES.rds`

This is not a `CytoML` or `cytoverse` problem. This is a problem with your system.
