### ISSUE TITLE
WSP files not opening properly - Can't find associated FCS files

### ISSUE THREAD

**Issue by Sithara85** [RGLab/CytoML#115]
Hi,

As you know we have been working on ~10,000 samples FCS files and generated gating set and workspace files. Now we were trying to open the wsp files in FlowJO and it is not opening properly. It shows a red 'X' on the filename in FlowJo and can't find associated fcs so we can't inspect the populations gated.

Do you have any idea what's going on? 

I have used below code to create the gating set and then ran docker/ singularity to create wsp files. As you notice I have used gsub to remove the white spaces in wsp files as save_gs was throwing error. But we tried to change the names with fcs name but it is not opening properly.

    template = gs_add_gating_method(
      gs_EM3,
      alias = "CD28Gate",
      pop = "+/-",
      parent = "root",
      dims = "CD28",
      gating_method = "mindensity",
      gating_args = "gate_range = c(1000,15000)")
    print(gs_pop_get_count_fast(gs_EM3))
    fcs_file <- basename(f)
    
    outputRoot = paste0(opt$outputDir, fcs_file)
    addedWSP = paste0(outputRoot,"_CT_EM3")
    addedWSP = gsub(" ", "_", addedWSP)
    print(paste0("adding and renaming nodes and writing to ", addedWSP))
    save_gs(gs_EM3,addedWSP)
    print (file.exists(addedWSP))
    
  }

Thank you,
Sithara

**Comment by gfinak** [comment]
@Sithara85 just following up, have you resolved this issue? Can you provide a simple reproducible example using one file?

**Comment by alexheubeck** [comment]
Hi @gfinak,

I'm getting a similar issue reconnecting files to FlowJo workspaces generated with CytoML. When you create the workspace file, it connects to the associated FCS files normally. But when a collaborator has opened the workspace on a different OS, when I go to open it again, nothing will reconnect. (I'm on Mac, and my collaborators are on Windows). 

Our workaround has been to open a new .wsp file, load in the files, and then copy the gating over from the CytoML generated .wsp file. 

I sent this to FlowJo to see if they could diagnose it, but they haven't gotten back to me yet. 

Thanks,

Alex

**Comment by Sithara85** [comment]
Hi Greg,

Yes, we resolved the issue a long time ago. I believe the issue was with some naming issue with FCS and associated WSP files.
