### ISSUE TITLE
Warning Message with  flowjo_to_gatingset(ws) 

### ISSUE THREAD

**Issue by EplisonG** [RGLab/CytoML#119]
Hi, 

I'm just starting to learn flowjo and how to use CytoML.  After opening the workspace with:  
```{r}
ws <- open_flowjo_xml('E:/Practice/project1.wsp')
```
I would like to read gates from FlowJo workspace with: 
```{r}
 gt <- flowjo_to_gatingset(ws, name = 1)
```
However,  A warning message appears:

```{r}
Warning message:
In flowjo_to_gatingset(ws, name = 1) :
  GatingSet contains different gating tree structures and must be cleaned before using it!
```
I try to find what the problem was but did not have clues. Could anyone give me some suggestions or hints? Thank you very much.
 
-Nancy

**Comment by gfinak** [comment]
The warning tells you that by importing "All Samples" you are making a GatingSet that contains samples with different gating schemes attached.
Generally importing "All Samples" is not recommended because of this.Import your different sample groups separately into separate Gating Sets.

**Comment by EplisonG** [comment]
> The warning tells you that by importing "All Samples" you are making a GatingSet that contains samples with different gating schemes attached.
> Generally importing "All Samples" is not recommended because of this.Import your different sample groups separately into separate Gating Sets.

Thank you very much for your kind reply, Greg. I change the name to other samples ( for example 2 or 3):
```{r}
 gt.samp2 <- flowjo_to_gatingset(ws, name = 2)
 gt.samp3<- flowjo_to_gatingset(ws, name = 3)
```
The warning message still appears. could it be a problem with the manually gated flowjo data? Thanks.

**Comment by gfinak** [comment]
It simply means that the samples in each of your sample groups are not consistently gated. They have different gating schemes in some way. 
It's advised to organize your sample groups so that samples in a group have a common gating scheme. I'm pretty sure this is even the use case for sample groups in FlowJo.

**Comment by EplisonG** [comment]
> It simply means that the samples in each of your sample groups are not consistently gated. They have different gating schemes in some way.
> It's advised to organize your sample groups so that samples in a group have a common gating scheme. I'm pretty sure this is even the use case for sample groups in FlowJo.

It's quite clear to me. I will go to check the gating strategies in FlowJo. Thank you, Greg. I truly appreciate it.
