### ISSUE TITLE
exporting to flowJo

### ISSUE THREAD

**Issue by mehrnoushmalek** [RGLab/CytoML#12]
Hello,
I am trying to export my gates to flowJo, and I have couple of questions.
My automated gating pipeline is based on estimateLogicle transformation, and it seems likes that it's unsupported for CytoML. So
1) Do I need to change it to flowJo_biexp_trans in order to be able to export and open it in flowJo or there's a way to translate logicle to what flowJo understands? Cause that would change my gating.
I even tried to pass estimateLogicle parameters to flowJo_biexp_trans(), but I get an error of invalid zeroChan (WidthBasis). I f I only change channelRange to be same as the range in estimateLogicle, it works,  but I'd prefer a better (cleaner) way.
2) Also when I use :
 gs <- transform(gs, trans.list) it seems like that it transforms the data on all nodes, does it keep the raw one as well?

These might be basic questions for you, but I'd appreciate it if you can help me.

**Comment by mikejiang** [comment]
Regarding to `estimateLogicle`, `CytoML` doesn't have problem by itself, it is `FlowJo` that doesn't have the direct support for it.  I could try to convert `etimateLogicle` to  `flowJo_biexp_trans`  during the exporting to see how it works. 
Before I add that support,  switching from `logicle` to `flowJo_biexp_trans` in your pipeline shouldn't affect your automated gating too much (except that you need to adjust some hard-coded gate thresholds).

We only keep one copy of the data, which is in the `transformed` scale. All the gated nodes are just a view of that data.  Can you tell me why you would need the raw data after the transformation is done?

**Comment by mikejiang** [comment]
What you have done is probably the best I can do internally. The bottom line is `CytoML` will export the gates in `raw` scale (by `inverse transform`). When you load your xml along with FCS files to `flowJo`, I believe what `flowJo` does is to use the `transformation` information provided by `CytoML` to scale the data and gates on the fly . Thus you should be able to change these parameters (e.g. `withBasis` and `neg`) in `flowJo` if you see the plots are not ideal.

`compensation` should be accessible if you did it through `compensate(gs, compobj)` call

**Comment by mehrnoushmalek** [comment]
Thanks, but can I have different parameters for each channel?
Also the widthBasis cannot be changed to w of estimateLogicle (.5 or .6). For my case, neg value of estimateLogicle is 0 as well. The only thing that it remains is the channelRange, which is not constant in estimateLogicle but based on looking at the plots I can set it to 4/5. Do you have any suggestion for that?

**Comment by mikejiang** [comment]
I think the easiest thing to do is to keep all default for `flowJo_biexp_trans` so you don't need to fiddle with these parameters. And change these hard coded gate thresholds by looking at the plots (which is what you did in the first run,right?)

**Comment by mehrnoushmalek** [comment]
I actually changed "channelRange =5". I will export it, and then open it in flowJo to see how it looks like. I will let you know, if the change doesn't come up as a warning/problem in flowJo.

**Comment by mehrnoushmalek** [comment]
One more question:

After adding each gate to the gatingSet I need to recompute the gatingSet right?
I don't get a difference between setGet(), and add().

**Comment by mikejiang** [comment]
Yes, `recompute` is required.
`setGate` is to rename or hide/unhide an existing gate.
`add` is to add a new gate

**Comment by mehrnoushmalek** [comment]
So, I tried the channelRange, but when I look at the flowJo files, some gates are wrong, as they are not positioned properly. I'm not sure if sth can be changed internally to fix that, or flowJo_biexp_trans parameters won't be given to flowJo. If that's the case, and nithing else is wrong, the only option would be to change my harcoded threshold.

Also when I look at the gating stratey parent population appear as population name when I use
add(gs, cd4.poly, parent="CD3"), CD4+ is noted as CD3 in flowJo.

**Comment by mikejiang** [comment]
@mehrnoushmalek , I add support for `logicle` , Pull the latest trunk branch and give it a try.
[here](https://github.com/RGLab/CytoML/blob/trunk/tests/testthat/test-flowJo.R#L41-L54) is the reproducible example. and here is the plots : original autogated(left) vs exported flowJo xml(right)
![image](https://cloud.githubusercontent.com/assets/1385649/21913921/aa42660c-d8e4-11e6-94de-0aec09e9f552.png)

**Comment by mikejiang** [comment]
as shown, the conversion from `logicle` to `flowJo biexp` is reasonable accurate based on both the `stats` and `plot`

**Comment by mehrnoushmalek** [comment]
Thanks a lot.
It depends on the latest version of flowWorkspace, and I can't get to install it.

**Comment by mehrnoushmalek** [comment]
I installed it manually, and it works perfectly.
I opened in in flowJo, everything is in its place, the only thing is that I have to manually change the widthBasis for some of the markers, as the w is too small (~-1000), and because of that everything was sqished (I have  attached the plot from flowJo). 
I am not good with flowJo, but I guess it's just a display thing in flowJo, as the gates are totally fine.

**Comment by mikejiang** [comment]
I've fixed that, please pull the latest version `1.1.5`, the `logicle` transformation is fully restored in `flowJo` as the plots shown below (left: `openCyto`, right : `flowJo`)
![image](https://cloud.githubusercontent.com/assets/1385649/21944812/f0ee142c-d98c-11e6-9708-722c5c88e4cd.png)

**Comment by mehrnoushmalek** [comment]
Maybe it's related to the flowJo version I'm using, but now I get lot of events in the margin, and I can't get to fix it in flowJo, however with the previous version, I was able to change the widthBasis.
![cd3-2 png](https://cloud.githubusercontent.com/assets/2798907/21947676/33f878b2-d99b-11e6-9c8b-bc810aec5e69.png)

**Comment by mikejiang** [comment]
Are they present as well in R? (make sure disable margin filtering when you plot it )
```
plotGate(gs, "CD3+", margin = FALSE)
```

**Comment by mehrnoushmalek** [comment]
![cd3](https://cloud.githubusercontent.com/assets/2798907/21948244/b5dcf508-d99e-11e6-8b26-8bf03dcabc2b.png)

This is what I get from the code above.

**Comment by mikejiang** [comment]
What do you mean by 'lot of events in the margin'?

**Comment by mehrnoushmalek** [comment]
When I use the transformation in the automated gating, is more like a estimateMedianLogicle, and there are different transformation filter for each parameters.
![cd3-3](https://cloud.githubusercontent.com/assets/2798907/21948369/a751c328-d99f-11e6-9012-cefbe018c5dd.png)

Margin events based on flowJo are the one on the axes the the ones exceeding the maximum in the range of channel.

**Comment by mikejiang** [comment]
@mehrnoushmalek , I now see your problem: Indeed, the `logicle` in `flowJo` seems to have such limitation that it can't bring some negative values into the display no matter how we adjust `width Basis`.
This issue remains even if I create `logicle` within `flowJo` from scratch. So it is probably something inherent within `flowJo` and has nothing to do with the process we convert from `flowCore::logicle` to `flowJo logicle`.

I will switch back to `biexp` and see if I can do better job to convert `flowCore::logicle` to `flowJo Biexp` so that you don't need to manually adjust it once xml is imported.

**Comment by mikejiang** [comment]
@mehrnoushmalek , pull the latest patch and try again. It should look better now, here is the updated `flowJo` imports for my previous example
![image](https://cloud.githubusercontent.com/assets/1385649/22038665/f8434c0c-dcb0-11e6-9047-ce991cd0200d.png)

**Comment by mehrnoushmalek** [comment]
@mikejiang, It works, and looks great. Thanks a lot for adding estimateLogicle and updating it.
