### ISSUE TITLE
How to close a flowjo_workspace ?

### ISSUE THREAD

**Issue by kforner** [RGLab/CytoML#123]
`open_flowjo_xml` states: 
> Open/Close a flowJo workspace

but I could not find a way to close it.
In this vignette https://rglab.github.io/flowWorkspace/articles/flowWorkspace-Introduction.html it is said:
>  the workspace must be explicitly closed using flowjo_ws_close()
 
But I could not find this function `flowjo_ws_close` . Ther's not even a match for it in this repo. 
My guess is that you forgot this function...

**Comment by mikejiang** [comment]
`flowjo_ws_close` is no longer needed, it will close when it is out of scope. I will update the docs.

**Comment by kforner** [comment]
Thank Mike for this quick reply. 
Just to comment, FWII you attached a destructor, so I think that it will be actually closed when garbage-collected, i.e. some undetermined time after it goes out of scope when the gc kicks in.
