### ISSUE TITLE
Ellipses coordinates are not correct in Gating Set after flowJo workspace parsing - v2.9.0

### ISSUE THREAD

**Issue by mlamarin** [RGLab/CytoML#142]
Dear All

Basically, using the last bioconductor:devel and CytoML version  **2.9.0**, ellipses are wrongly located (in the FSC-A, SSC-A) space after flowJo workspace parsing.

I built theoretically a reproducible example in the GitHub project below:

https://github.com/mlamarin/cytoml_bug_flowjo_ellipse/blob/main/flowjo_ellipse_bug.R

The code was used to work correctly, at least in R_3.6.1 (ellipses gates were correctly placed)
Thanks for the fantastic work you  have already done.

HTH
Marc

**Comment by mikejiang** [comment]
Thank you for reporting the bug! Looking into it.

**Comment by mikejiang** [comment]
addressed by https://github.com/RGLab/CytoML/pull/143

**Comment by mikejiang** [comment]
@mlamarin Somehow I cannot request you to review this PR, can you assign yourself and approve it?

**Comment by mikejiang** [comment]
Merged to master branch. Also pushed to bioconductor.
