### ISSUE TITLE
cytobank.default.scale parameter is broken

### ISSUE THREAD

**Issue by mikejiang** [RGLab/CytoML#19]
On 05/10/2017 05:33 AM, Chris Ciccolella wrote:
> Ah, so, Cytobank does accept the scale settings on a per-gate basis in the gatingml, it just doesn't set the experiment scales to match. The end result is that the scales for the gate itself are set however you like, but you then have to go into the experiment and change them to match the gate. It's a pain, but it's doable. So put another way, there is no reason that the package couldn't have this functionality. To clarify, the package itself currently doesn't support this and that's a known issue?
>
> Regarding scale presets, it actually depends on the cytometer that produced the files. A typical fluorescent preset for a variety of cytometers is what you provided. Cytof, though, has min of -5, max of 12k, and scale argument of 5. 
>
> Thanks!
> Chris
>
> Sent from mobile
>
>> On May 10, 2017, at 2:06 AM, Mike <wjiang2@fhcrc.org> wrote:
>>
>> It won't work unless cytobank can parse the `scale` information from the gatingML and set the `Experiment Scales` accordingly. As far as I know from my last try, cytobank presets `Arcsinh` with `scale argument = 150` and `range = (-200, 262144.0)` and ignores what's actually provided in gatingML.
>>
>>
>>> On 05/08/2017 09:53 PM, Chris Ciccolella wrote:
>>> Hi Mike,
>>>
>>> Hope you're doing well. Quick question for you regarding CytoML.
>>>
>>> We're having trouble with the cytobank.default.scale argument being set to false. I think setting this argument to false will be critical for proper transfer of gates when any gating happens outside the boundary of Cytobank default scales, which will be reasonably often. Do you have any insight for this error message (attached) and are you certain that the functionality works for you?
>>>
>>> Chris
>>

**Comment by mikejiang** [comment]
I can reproduce the error
```r
> GatingSet2cytobank(gs, outFile, cytobank.default.scale =F) #type by default is 'cytobank'
 Show Traceback
 
 Rerun with Debug
 Error in FUN(X[[i]], ...) : 
  can't find the transformation function in GatingSet to inverse the range for :G560-A 
```
The error message wasn't accurate( I will fix that), it did find the transformation and actually found two of them: one is named as prefixed `<G560-A>` and another non-prefixed version `G560-A`, (because somehow `flowJo` stores both) and when the gates were converted to `gatingML` by `flowUtils`, the original prefix and suffix (i.e. `<>`) was always discarded and in favor of  its own convension `comp_G560-A`, which was why I did fuzzy matching between the them in order to find the correct transformation for that channel.
Now looks like I do need to do a little string manipulation to find the exact match.

**Comment by mikejiang** [comment]
I've pushed the fix and now cytobank.default.scale = F should work. Here is the reproducible example
```r
library(CytoML)
library(flowWorkspace)
dataDir <- system.file("extdata",package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
Rm("CD8", gs)
#output to cytobank
outFile <- "~/cytobank/test.xml"
GatingSet2cytobank(gs, outFile, cytobank.default.scale =F)
```
And I've checked the `Illustrations-->Gating Hierarchy` cytobank web page, all the stats and gates look ok to me. 

But the gates won't be visible at `Gating` page unless the `Scales` is manually corrected so that it is consistent with the one stored at the gate level. I wrote a convenient wrapper 'range' to retrieve the raw scale from `GatingHierarchy` object for that purpose (since openCyto only stores the transformed data by default). 
```r
range(gh, raw.scale = TRUE) #inverse transform the range to the raw scale
```
see `?range.GatingHierarchy` for the details.

**Comment by tjburns08** [comment]
I'm going to miss Chris. Mike, I'll be chatting with you directly, and @katdrake will be the person I report to. Looking forward to working with you more. -Tyler
