### ISSUE TITLE
Quadrant gate export to flowjo

### ISSUE THREAD

**Issue by Jincheng2009** [RGLab/CytoML#20]
After export gating set to flowjo workspace ` GatingSet2flowJo`, the quadrant gate is parsed by FlowJo as four independent rectangular gates. I compared the xml specification between `CytoML` and FlowJo:

The difference is as below:

Quadrant gate in FlowJo:
<Gate gating:id="ID1302626923" gating:parent_id="ID717907167" >
  <gating:RectangleGate eventsInside="1" annoOffsetX="0" annoOffsetY="0" tint="#000000" isTinted="0" lineWeight="Normal" userDefined="1" percentX="0" percentY="0" >
    <gating:dimension gating:max="86.71224060277042" >
    <data-type:fcs-dimension data-type:name="Comp-PE-Texas Red-A" />
    </gating:dimension>
  <gating:dimension gating:min="546.4788302000138" >
  <data-type:fcs-dimension data-type:name="Comp-PE-Cy7-A" />
</gating:dimension>
</gating:RectangleGate>
</Gate>

Quadrant gate in CytoML **(difference highlighted)**:
<Gate gating:id="ID1397615987" gating:parent_id="ID158210715" >
<gating:RectangleGate eventsInside="1" annoOffsetX="0" annoOffsetY="0" tint="#000000" isTinted="0" lineWeight="Normal" userDefined="1" percentX="0" percentY="0" >
<gating:dimension gating:min="38.9175232999206" **gating:max="2.147483647E9"** >
<data-type:fcs-dimension data-type:name="Comp-PE-Texas Red-A" />
</gating:dimension>
<gating:dimension **gating:min="-2.147483647E9"** gating:max="337.826512315656" >
<data-type:fcs-dimension data-type:name="Comp-PE-Cy7-A" />
</gating:dimension>
</gating:RectangleGate>
</Gate>

Could this be improved? I am not sure whether this is more related to `flowWorkspace` or `flowCore`

Thank you.

**Comment by mikejiang** [comment]
There is no such concept as `quadgate` in `GatingSet`, instead, they are already stored as rectangle gates. 
So you wanted to find out why there is difference for the same rectangle gate between the xml exported by CytoML and the xml generated by flowJo. Can you make sure you are looking at the same population node (quadrant)?

**Comment by Jincheng2009** [comment]
Hi Mike,

Thanks for the prompt response. Yes, I am sure I am looking at the same population node.
I did some experiments yesterday and here is what I found:

1. There is no such concept as `quadgate` in `GatingSet` as well as `flowjo workspace`, they are both stored as 4 rectangular gates.

2. In FlowJo, there is an implicit difference between the typical rectangular gate and rectangular gates rendered from `quadgate`

**Typical rectangular gate:**
<gating:dimension gating:min="10" gating:max="100" >
<data-type:fcs-dimension data-type:name="Comp-PE-A" /></gating:dimension>
<gating:dimension gating:min="20" gating:max="200" >
<data-type:fcs-dimension data-type:name="Comp-FITC-A" /></gating:dimension>

**Rectangular gates from `quadgate`:**
<gating:dimension gating:min="10"  >
<data-type:fcs-dimension data-type:name="Comp-PE-A" /></gating:dimension>
<gating:dimension gating:max="200" >
<data-type:fcs-dimension data-type:name="Comp-FITC-A" /></gating:dimension>

The later one only specifies the center point of the quandrant, and refers to `min` and `max` to decide which quad is this rectangle. For the example above, it refers to PE+FITC- region.

3. The export from CytoML saves rectangular gate from both cases in the same way. Therefore, opening it in flowjo render `quadgate` as 4 rectangular gates. 

4. I manually changed the `rectangular gate` in CytoML export file to the flowjo format, and then flowjo can render it as a `quadgate`. Note that here I need to change the format for all the four rectangular gates to make it work.

I used FlowJo 10.2 Windows for the tests above. This issue does not affect any correctness of the results (e.g. gating percentages). It is just when the users want to adjust `quadgate` in flowjo, they need to move the gate four times instead of one.

**Comment by mikejiang** [comment]
I see. We need to figure out the robust way to identify/reconstruct quadgate from those independent rectangle gates. Can I ask where those quadgates come from? Were they parsed from flowJo xml initially or generated by `openCyto` automated gating method? Could you briefly tell us the application background and motives , which may help us better design our tools.

**Comment by Jincheng2009** [comment]
I am using `flowWorkspace` to build automated gating and export it to flowjo using `CytoML`. `quadGate` refers to the one in `flowCore` and when added to `gatingSet`, it becomes 4 rectangular gates. In addition, if I open a native flowjo workspace using `parseWorkspace` and export the `gatingSet` using `GatingSet2flowJo`, the quadGate is also lost (i.e. showed up as 4 rectangular gates in flowjo).

The motive is to let the end user easy to adjust the `quadgate` if automated gating does not work properly. 

I am not familiar with the implementation. But either we can fix it in `flowWorkspace` to distinguish the `rectgate` from `quadgate`, or we can fix it in `CytoML` to detect the `rectgates` that should be formatted as `quadgate`. I am willing to help and test more if you need.

Thank you.

**Comment by mikejiang** [comment]
Try to pull the latest `CytoML` and `ggcyto` and let me know if it works with `flowJo` ( my `FJ` expires and is waiting for renewal)

**Comment by Jincheng2009** [comment]
I just tested `GatingSet2flowjo` and it works. 
Great, thanks a lot.
