### ISSUE TITLE
Tailoring per file appears to be broken

### ISSUE THREAD

**Issue by mikejiang** [RGLab/CytoML#21]
On 06/19/2017 04:23 PM, Chris Ciccolella wrote:
>
> Maybe you can double check this but we can't get it to work. This is when you have the same gate but in a slightly different location between samples. This happens frequently between donors or between acquisition collection dates or instruments.

**Comment by mikejiang** [comment]
It actually works for me. Maybe you can provide an example.

Here is my reproducible example: 

Firstly, we generate the GatingSets containing two samples by parsing flowJo workspace
```r
library(CytoML)
library(flowWorkspace)
dataDir <- system.file("extdata",package="flowWorkspaceData")
xml <- list.files(dataDir, pattern = "manual.xml",full = TRUE)
ws <- openWorkspace(xml)
gs <- parseWorkspace(ws, name = 4)
gs
Rm("CD8", gs)
```
Now we modify the `CD3+` gate so that gates for the two samples are slightly different
```r
g <- getGate(gs, "CD3+")
m <- g[[2]]@mean
m[[1]] <- 3000
g[[2]]@mean <- m
setGate(gs, "CD3+", g)
recompute(gs) # update the gating
plotGate(gs, "CD3+") # visualize the difference
```
![image](https://user-images.githubusercontent.com/1385649/28191601-272492ea-67e6-11e7-8fb9-0c38d83cc8a6.png)
After exporting it to gatingML and loading it into cytobank (https://community.cytobank.org/cytobank/experiments/65311 , experiment is shared with you)
 we can see the difference is kept and represented as tailored gates.
```r
outFile <- "~/cytobank/test.xml"
GatingSet2cytobank(gs, outFile)
```
![image](https://user-images.githubusercontent.com/1385649/28191815-7646b64a-67e7-11e7-87ca-18902da9867d.png)

**Comment by cciccole** [comment]
@mikejiang Could you share your WSP? We'll give it a try on our end and see if it works.

**Comment by mikejiang** [comment]
The xml and FCS are from `flowWorkspaceData` package which you can install through bioconductor. The code I pasted should be reproducible by you .

**Comment by cciccole** [comment]
@katdrake to take over since I'm moving on from cytobank

**Comment by mikejiang** [comment]
I finally got to the bottom of the issue. In your use case, fcs file was renamed by `flowJo` ,e.g. `pbmc_lrs005_unstim1_unstim_Ungated.fcs` --> `PBMC_LRS005_Unstim1.fcs`, or the other way around, not sure which is the old and which is new. Anyway, `flowJo` workspace uses the short version (``PBMC_LRS005_Unstim1.fcs`), which is recorded in FCS keyword `$FIL`, so `openCyto` follows the same rule and stored the short name into `GatingSet`.
When exporting to `gatingML`, the tailored gate is associated with this shortname by default, which is why they were not picked up by `cytobank`.

I am not going to ask `cytobank` to add this behavior of matching fcs by keyword since it is an easy fix on my end by simply switching to the long name, which fixes the problem as shown below. 
![image](https://user-images.githubusercontent.com/1385649/31968435-ee4b177e-b8c5-11e7-9f65-c6b2b848e344.png)![image](https://user-images.githubusercontent.com/1385649/31968448-016acba6-b8c6-11e7-997e-9e58cc16b665.png)![image](https://user-images.githubusercontent.com/1385649/31968469-1130d77e-b8c6-11e7-90f7-dda1117a3648.png)

**Comment by tjburns08** [comment]
@mikejiang definitely something I didn't expect. Thanks for your help. I've confirmed that it works on my end after your commit.
