### ISSUE TITLE
Gates drawn on CyTOF files are not supported by CytoML (perhaps all files without compensation?)

### ISSUE THREAD

**Issue by cciccole** [RGLab/CytoML#24]
Gates could not be transferred with the CytoML package when CyTOF files were being used. Errors related to compensation popped out. 

```
GatingSet2cytobank(gs, x.xml)
Error in initialize(value, …) : object ‘compId’ not found
```

It’s possible that this is because there is no flowjo compensation in these situations. An empty placeholder compensation matrix (spillover matrix) was inserted in one such file and the errors persisted. A natural next step would be to try inserting a compensation matrix with actual values in it to see if the errors persist. This hasn't been attempted yet.

This file [(Marrow1_Mature CD8+ T_cells.fcs.zip)](https://github.com/RGLab/CytoML/files/1154536/Marrow1_Mature.CD8.T_cells.fcs.zip) is a test file taken from [this Cytobank experiment](https://community.cytobank.org/cytobank/experiments/46259).

**Comment by mikejiang** [comment]
Can you provide the `fj` xml or the archived `GatingSet` that I can reproduce the error?

**Comment by cciccole** [comment]
@katdrake to take over since I'm moving on from cytobank
