### ISSUE TITLE
Problem installing from trunk

### ISSUE THREAD

**Issue by dtebaykin** [RGLab/CytoML#29]
R version: 3.4.2 on Mac OS X 10.12.6 Sierra.

The older version (0.5.40 of 2011-03-04) of flowWorkspace works, but it does not have the logtGml2 that Cytobank uses these days. As a result I cannot import the Cytobank gates into R.

When following the installation steps:
biocLite("openCyto")
install_github("RGLab/flowWorkspace", ref="trunk")
install_github("RGLab/openCyto", ref="trunk")

openCyto installs properly, but flowWorkspace installation fails with the following text:

The error message:
R_API.cpp:42:21: error: non-const lvalue reference to type 'GatingHierarchy' cannot bind to a temporary of type 'GatingHierarchy *'
                GatingHierarchy & gh = gsPtr->getGatingHierarchy(sn);
                                  ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
R_API.cpp:44:68: error: member reference type 'GatingHierarchy *' is a pointer; did you mean to use '->'?
                StringVec allNodes = gsPtr->getGatingHierarchy(sampleNames.at(i)).getPopPaths(REGULAR, isFullPath, true);
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                                                                 ->
R_API.cpp:101:14: error: no viable conversion from 'valarray<double>' to 'vector<double>'
                ARRAY_TYPE tmp = cal.getX();
                           ^     ~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:530:5: note: candidate constructor not viable: no known conversion from 'valarray<double>' to 'initializer_list<value_type>' (aka 'initializer_list<double>') for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:542:5: note: candidate constructor not viable: no known conversion from 'valarray<double>' to 'const std::__1::vector<double, std::__1::allocator<double> > &' for 1st argument
    vector(const vector& __x);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:548:5: note: candidate constructor not viable: no known conversion from 'valarray<double>' to 'std::__1::vector<double, std::__1::allocator<double> > &&' for 1st argument
    vector(vector&& __x)
    ^
R_API.cpp:177:21: error: non-const lvalue reference to type 'GatingHierarchy' cannot bind to a temporary of type 'GatingHierarchy *'
                GatingHierarchy & gh = gsPtr->getGatingHierarchy(*it);
                                  ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11 warnings and 4 errors generated.
make: *** [R_API.o] Error 1
ERROR: compilation failed for package ‘flowWorkspace’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace’
Installation failed: Command failed (1)

**Comment by mikejiang** [comment]
You need to install the latest `RProtoBufLib` and `cytolib`

**Comment by dtebaykin** [comment]
Thank you, this did the trick:
install_github("RGLab/RProtoBufLib", ref="trunk")
install_github("RGLab/cytolib", ref="trunk")
install_github("RGLab/flowWorkspace", ref="trunk")

**Comment by dtebaykin** [comment]
Actually, the flowWorkspace package still gives me an error:

clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o flowWorkspace.so R_API.o R_GatingHierarchy.o R_GatingSet.o RcppExports.o getSingleCellExpression.o setCounts.o /Library/Frameworks/R.framework/Versions/3.4/Resources/library/RProtoBufLib/lib/GatingSet.pb.o /Library/Frameworks/R.framework/Versions/3.4/Resources/library/RProtoBufLib/lib/libprotobuf.a -lxml2 -lz -lpthread -licucore -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: ignoring file /Library/Frameworks/R.framework/Versions/3.4/Resources/library/RProtoBufLib/lib/GatingSet.pb.o, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Library/Frameworks/R.framework/Versions/3.4/Resources/library/RProtoBufLib/lib/GatingSet.pb.o
if [ `uname -s` = 'Darwin' ]; then install_name_tool -change /usr/local/clang4/lib/libc++.1.dylib /usr/lib/libc++.1.dylib flowWorkspace.so; fi
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘flowWorkspace’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace/libs/flowWorkspace.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace/libs/flowWorkspace.so, 6): Symbol not found: __ZN2pb11ellipseGate17default_instance_E
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace/libs/flowWorkspace.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspace/libs/flowWorkspace.so
Error: loading failed
Execution halted

**Comment by mikejiang** [comment]
Sorry, included the object file in repo by mistake. Try to re-install `RProtoBufLib` from github.

**Comment by dtebaykin** [comment]
Ok, I was able to install the libraries from github. I now have:
flowWorkspace version 3.27.6
openCyto version 1.17.2
flowCore version 1.45.2

My original problem was not being able to import a Gating-ML 2.0 file from Cytobank into R, the error: Error in FUN(X[[i]], ...) : 
  Don't know how to inverse transformation: logtGml2

I was hoping the updated libraries would be able to deal with that, but the error persists.

**Comment by mikejiang** [comment]
see #30
