### ISSUE TITLE
Updating bioconductor version

### ISSUE THREAD

**Issue by dtebaykin** [RGLab/CytoML#34]
I am trying to compare values from FCS files after importing gates from Cytobank (which applies asinhtGml2 transform) to a static value (Example: 100). Applying the asinhtGml2 to 100 doesn't seem to work. I found the transform(..., inverse = TRUE) option in the

install_github("RGLab/flowWorkspace", ref="trunk")
install_github("RGLab/openCyto", ref="trunk")

versions, but after updating my GatingML file was not recognized as a valid XML and read.flowSet failed to import the FCS files. Is there a plan for updating the bioconductor versions of these libraries to more recent stable versions? If not, what steps should I take to reverse the data transformations after applying gates?

**Comment by gfinak** [comment]
Bioconductor versions are updated with every bioconductor release. 
Until then, the bioconductor development branch tracks this github version.. you can use that instead of the release branch.

**Comment by mikejiang** [comment]
I am not exactly sure what specific problems you are having. Please post your code and errors as well as `sessionInfo`(preferred to be uploaded as the attached file to keep the thread visually compact)

**Comment by dtebaykin** [comment]
Sorry for the late reply, I was able to fix the code on my end. Are the flowCore/flowWorkspace/openCyto packages being actively worked on? Pulling the latest trunk might not be the best solution for me in case function signatures and/or behaviors change.

**Comment by gfinak** [comment]
They are being actively developed, but they are mature so we actively ensure backward compatibility.
