### ISSUE TITLE
Error in orig_params[ind] : invalid subscript type 'list' uploading gatingML from cytobank

### ISSUE THREAD

**Issue by lbrady5** [RGLab/CytoML#37]
Tried uploading gatingML file exported from cytobank using the "read.gatingML.cytobank" function. 
Received this error:
Error in orig_params[ind] : invalid subscript type 'list' uploading gatingML from cytobank
Also tried uploading gatingML using "cytobank2GatingSet" and received same error. 
Has anyone seen this before?

**Comment by gfinak** [comment]
Reproducible example please...

**Comment by lbrady5** [comment]
We were able to troubleshoot the issue. It was occurring due to characters within the Channel names. When removed, this error was resolved.
