### ISSUE TITLE
Unable to parse any XML input

### ISSUE THREAD

**Issue by abbatidanilo** [RGLab/CytoML#46]
I used the following command CytoML::GatingSet2flowJo(manual_gs, outFile = "./manual_gs.xml") to generate an .xml file for a gatingset.
The error in the uploaded file seems to be  on line 20: The prefix "transforms" for element "transforms:spilloverMatrix" is not bound.
The attached file is with the txt extension (actually is the xml file I'm trying to parse)
[manual_gs-sublime2.txt](https://github.com/RGLab/CytoML/files/2514907/manual_gs-sublime2.txt)
I am currently using  ‘CytoML’ version 1.7.9 within R-3.5.1

**Comment by gfinak** [comment]
What exactly is the problem you are having? I'm able to read the xml file you uploaded in FlowJo.
![image](https://user-images.githubusercontent.com/1385593/47513771-cbdd2680-d833-11e8-86f5-069ffca0e6c6.png)

Are you trying to read in an xml file created by `GatingSetflowJo` using `flowWorkspace` ? If so, why?

**Comment by gfinak** [comment]
FlowJo xml is not GatingML. The only thing that we strive to guarantee is that GatingSet2FlowJo will create an xml file that can be read by FlowJo.
