### ISSUE TITLE
Get untransformed data with getData

### ISSUE THREAD

**Issue by hartmannfj** [RGLab/CytoML#47]
Hi all,

I am reading in an xml file created from cytobank with read.gatingML.cytobank() and subsequently create a gatingSet with cytobank2GatingSet(). When I then call getData on this gatingSet, the channels that are used for gating get transformed, whereas other channels stay untransformed. 

Is there an easy way to prevent transformation when calling getData()?

Cheers, Felix

**Comment by mikejiang** [comment]
Data is transformed during `cytobank2GatingSet` instead of `getData` call. In order to get raw scale, you will have to do the inverse transform on your own. e.g.
```r
fs <-  getData(gs)
#since cytobank has one set of global transformation defined for entire GatingSet
#we can safely extract the trans from the first sample
trans.inv <- getTransformation(gs[[1]], inverse = TRUE) 
translist <- transformList(names(trans.inv), trans.inv)
fs.raw <- transform(fs, translist)
```

**Comment by hartmannfj** [comment]
Thanks for the quick answer, works great!
