### ISSUE TITLE
Saving derived parameters after GatingSet2flowJo

### ISSUE THREAD

**Issue by mehrnoushmalek** [RGLab/CytoML#51]
Hello,

I'm setting up a shinyApp fir automated analysis, and fter running the analysis, the results can be downloaded.
Everything will be saved in a temp directory using tempdir(). I was able to save everything except the derived parameters, as they will be saved like "./sample****.EPA.csv" and I'd like to have the option of removing "./" so everything will be saved in a same folder. Is there a work around this?

Thanks in advance,

Mehrnoush

**Comment by mikejiang** [comment]
Are you referring to `GatingSet2flowJo`?csv is saved at the same path as xml (specified by `outFile`).

**Comment by mehrnoushmalek** [comment]
@mikejiang  yes `GatingSet2flowJo`. I can see it in the output message that it gets saved in "./"
`DerivedParameter: ./sample*.EPA.csv`
 but `./` does not work with tempdir().

**Comment by mikejiang** [comment]
What's your GatingSet2flowJo call look like? I need you prefer more information of the context

**Comment by mehrnoushmalek** [comment]
It's ` GatingSet2flowJo(gs, outFile =outfile )`.

**Comment by mikejiang** [comment]
If you give a filename without the path, it will write the xml and csv to the current working directory. Are you saying that you see them in different folder?  
How do I reproduce your issue? Everything seems to work fine in a regular R console. (Not sure about the context environment or settings in your shinyApp)

**Comment by mehrnoushmalek** [comment]
@mikejiang  I got it fixed with manually adding derived parameters names to my zip files.

**Comment by mikejiang** [comment]
It's very unclear to me
* what exactly the issue is
* how it is triggered
* how it is fixed
Without the detailed the information and reproducible code, I don't know how this issue report can be of any help to anyone.

**Comment by mehrnoushmalek** [comment]
- Issue was with the files being saved by using `dirname(outfile)`
-For shinyApps the code needs to know the exact name of the file with the path, and "./" made me confused. I wanted to have the option of giving the path myself
- I ended up manually adding the names of derived parameters with the correct path to fix the issue. 
- If you think it's not useful to anyone, go ahead and delete.

**Comment by mikejiang** [comment]
Ok, I think (finally) that might be the problem you were facing.
You were trying to copy (or download) the csvs along with xml. And for csv files,  you know the path (i.e. the same folder as xml), but not the filenames (which are actually recorded in the xml).
So you were relying on the R messages printed to R console (i.e. `DerivedParameter: ./sample*.EPA.csv
`) to parse out the filenames.
I don't think the R messages can be treated as reliable source for the programmatic purpose. Instead, we can either provide the API to return these filenames for you or supply `GatingSet2flowJo`  with `out_dir` instead of `outFile` as the second argument, to which the xml and csvs will all be written.

**Comment by mehrnoushmalek** [comment]
I would not use R messages for programming, but they should be informative enough.
Returning back the file names would be a nice option to have for `GatingSet2flowJo`.

**Comment by mikejiang** [comment]
I can easily expand `./sample*.EPA.csv` to the absolute full path in the R message, if that is all you need for your particular use case.

**Comment by mehrnoushmalek** [comment]
That would be nice, and also an option to return back the filename if needed.
Thanks!
