### ISSUE TITLE
Error in gatingset_to_flowjo(gs, outfile)

### ISSUE THREAD

**Issue by mehrnoushmalek** [RGLab/CytoML#59]
Hello,

I updated my flowWorkspace, Cytolib, CytoML packages, and I get the error of :
`Error in getSpilloverMat(gh) : 
  trying to get slot "spillover" from an object of a basic class ("matrix") with no slots`
When I try `getCompensationMatrices(gs[[1]])`, I get my comp matrix, but not an spillover object ( where the code tries to access ` mat <- compobj@spillover`). I looked at the code and my `gh@compensation` returns back a list that has compensations of all my samples. I couldn't find anything in the man page that got changed with the new version, that should be added.
Is there anything that I should add to the gatingSet to avoid this error? I don't have the problem with the older version of flowWorkspace( before changing functions name ,...).

p.s. I apply the compensation on the `gs`.

**Comment by mikejiang** [comment]
This may be related to the changes from RGLab/flowWorkspace@bc3eab66e63ed67a9d70a14699e3688225fd3752
I will try to reproduce the error and find a fix for you.

**Comment by jacobpwagner** [comment]
I'm not sure it is related to RGLab/flowWorkspace@bc3eab6, as I can reproduce after reverting to just before that, but only when compensating a `GatingSet` with a simple spillover matrix as opposed to a `compensation` object. As you highlighted, @mehrnoushmalek , it looks like the code for `gatingset_to_flowjo()` currently assumes that the `compensation` slot for the `GatingSet` is a `compensation` object and not a matrix. I'll get a fix up pretty soon.

**Comment by jacobpwagner** [comment]
@mehrnoushmalek , 1386968 should fix it. But if that's not the case, let me know and I'll re-open this.
