### ISSUE TITLE
Support FlowJo v9 for GatingSet2flowJo()

### ISSUE THREAD

**Issue by malisas** [RGLab/CytoML#66]
It would be helpful if `GatingSet2flowJo()` could export a GatingSet to a FlowJo v9 workspace/xml. Maybe a `version = 9` option?
   
My lab still primarily uses FlowJo v9, so this would allow me to modify or add gates in openCyto and then export to FlowJo 9 so that my labmates and I can make further changes or layouts.
This would also help with converting back-and-forth between FlowJo v9 and v10, a task which is not supported by FlowJo.

Thanks!

**Comment by gfinak** [comment]
This is not on the roadmap since V9 is now a legacy version.
