### ISSUE TITLE
cytobank2GatingSet Error

### ISSUE THREAD

**Issue by JehadAldahdooh** [RGLab/CytoML#68]
I run cytobank2GatingSet function with a given xml and fcs files but I get an error as follows:
![image](https://user-images.githubusercontent.com/21081480/67398042-c8998980-f5b2-11e9-865d-368bdc400aff.png)

Code is here:
library(CytoML)
xmlfile <- "Desktop/flowcyto/CytExp_12536_gating.xml"
fcsFiles <- "Desktop/flowcyto/20170423-053410iQueScreenerPLUS-VBR.fcs"
gs <- cytobank2GatingSet(xmlfile, fcsFiles,emptyValue = F)

May I ask you how I fix it? reading the fcs file is done inside the function then how to modify the inner code if it is not provided through the parameters?

Thanks a lot

Best Regards,

Jehad

**Comment by mikejiang** [comment]
Try the fix from trunk branch

**Comment by JehadAldahdooh** [comment]
Thanks for the reply, so from trunk not from BiocManager.

I actually tried to install it from GitHub but I get the following error:
![image](https://user-images.githubusercontent.com/21081480/67419157-d7913380-f5d4-11e9-9136-cb326f60ba8e.png)

Any help?

Thanks

**Comment by mikejiang** [comment]
install cytolib from github as well

**Comment by JehadAldahdooh** [comment]
ok I will try and hope it works :) 

Thanks a lot

**Comment by JehadAldahdooh** [comment]
installing it using R cmd command gives an error:
![image](https://user-images.githubusercontent.com/21081480/67420181-c812ea00-f5d6-11e9-8cab-35a35bf69be1.png)

**Comment by mikejiang** [comment]
`devtools::install_github("RGLab/cytolib", ref = "trunk")`

**Comment by JehadAldahdooh** [comment]
so I installed cytolib using devtools::install_github("RGLab/cytolib", ref = "trunk") as follows:
![image](https://user-images.githubusercontent.com/21081480/67485104-13c6a180-f672-11e9-8e68-fb9191ab2be5.png)

and after that I tried to install flowWorkspace but I get the a lot of warning messages and the following error at the end as follows:
![image](https://user-images.githubusercontent.com/21081480/67485301-66a05900-f672-11e9-8f61-cfa894262d84.png)

Any help?

Thanks a lot

**Comment by gfinak** [comment]
Please make a habit of reading the error messages before posting.
In this case, just as in the others, they clearly state the problem. .
You have a package that is not up to date. 
In this case, it's telling you the flowCore package it finds on your system is not the version it expects.
FlowCore is also on github, and you need to upgrade it.

**Comment by JehadAldahdooh** [comment]
Sorry for that I didn't pay attention for that.

Now it works :)

Thanks a lot
