### ISSUE TITLE
missing example files

### ISSUE THREAD

**Issue by JehadAldahdooh** [RGLab/CytoML#70]
Hi;

In the folder extdata, I didn't find the  Cytobank xml file and fcs files as well. 
Would it be possible to tell me where I can find the files used in the following code:
library(CytoML)
xmlfile <- system.file("extdata/cytotrol_tcell_cytobank.xml", package = "CytoML")
fcsFiles <- list.files(pattern = "CytoTrol", system.file("extdata", package = "flowWorkspaceData"), full.names = T)
gs <- cytobank2GatingSet(xmlfile, fcsFiles)

Look forward to hearing from you.

Thanks a lot

Best Regards,

Jehad

**Comment by mikejiang** [comment]
It is now bundled into a `acs` cytobank experiment file , to extract the file, see https://github.com/RGLab/CytoML/blob/trunk/tests/testthat/test-cytobank.R#L31-L33

**Comment by jacobpwagner** [comment]
@JehadAldahdooh , the `README` and docs have been updated to reflect this change in 71ccddc2c340f60933597e373fb77d7465a312c5

**Comment by JehadAldahdooh** [comment]
Thanks for the reply. 

I have an error when I 

![image](https://user-images.githubusercontent.com/21081480/67989583-f4181600-fc3b-11e9-87c6-87266680399e.png)

**Comment by jacobpwagner** [comment]
Curious. I used your exact same code snippet (on the example data) and the tree and gate plot just fine:
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67989853-61eb2000-fbf1-11e9-8e80-270711715138.png)
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67989862-67e10100-fbf1-11e9-86aa-a17ce77ba440.png)
I'll try with your data, but could you post your `sessionInfo()` output?

**Comment by jacobpwagner** [comment]
Same for your data, it seems to load and plot just fine in my hands, but if I can examine package versions I can try to see what the difference is
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67990306-bba01a00-fbf2-11e9-907a-83ccd5614ad0.png)
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67990313-c22e9180-fbf2-11e9-91ce-5d5c2ffad3e5.png)

**Comment by JehadAldahdooh** [comment]
Thanks for the reply here is the session info 
![image](https://user-images.githubusercontent.com/21081480/67990500-c7b1c900-fc3e-11e9-9274-1e4ae279173c.png)

**Comment by jacobpwagner** [comment]
Thanks. Could you please give me the output of `warnings()` as well?

**Comment by JehadAldahdooh** [comment]
![image](https://user-images.githubusercontent.com/21081480/67990764-8968d980-fc3f-11e9-89c6-9195aa19ebb9.png)

**Comment by jacobpwagner** [comment]
Huh. Are any plots working? Are there points in the plots when you just do this?:
`plot(mtcars)`

**Comment by JehadAldahdooh** [comment]
![image](https://user-images.githubusercontent.com/21081480/67991669-ace15380-fc42-11e9-94f7-bde0f31b139a.png)

**Comment by jacobpwagner** [comment]
How about the output `dev.list()`, `dev.cur()`, and `par()` (just copy-paste the text, no need for an image)? Have you tried `graphics.off()` (or just restarting R) before trying to plot again?

**Comment by jacobpwagner** [comment]
Oh, you're also on macOS High Sierra. Have you upgraded the OS recently and not reinstalled XQuartz? Can you give me the output of this `capabilities("X11")`?

**Comment by JehadAldahdooh** [comment]
> capabilities("X11")
 X11
TRUE

**Comment by jacobpwagner** [comment]
Does `ggcyto::autoplot` also produce empty plots? Or `ggplot2` for that matter? Do these succeed?:

`ggcyto::autoplot(gs[[1]])`

```
d <- ggplot(diamonds, aes(carat, price))
d + geom_hex()
```

**Comment by JehadAldahdooh** [comment]
Awesome, it works now  👍 

Here is a snapshot:

![image](https://user-images.githubusercontent.com/21081480/68046402-778d4200-fce4-11e9-9980-b97e42bddba8.png)


Thanks a lot for your help

**Comment by jacobpwagner** [comment]
No problem. Sorry it took a little while to troubleshoot.

**Comment by k-motwani** [comment]
Hello, out of curiosity is this test still functional? I'm also looking for the cytotrol_tcell_cytobank xml and dataset. 

https://github.com/RGLab/CytoML/blob/devel/tests/testthat/test-cytobank.R
I think this might be the same script mentioned in `https://github.com/RGLab/CytoML/issues/70#issuecomment-547057502`

**Comment by mikejiang** [comment]
these tests are only meant to be invoked from our local machine, if you're trying to work on cytobank XML, I assume you already have access to their portal, thus should be able to generate your own example output files from their platform.
