### ISSUE TITLE
gatingset_to_flowjo doesn't work with windows

### ISSUE THREAD

**Issue by htanaka1234** [RGLab/CytoML#88]
Hi,

I have a problem with the function _gatingset_to_flowjo()_ in CytoML package for Bioconductor version: Release (3.11). 
This returns an error in windows environment;
  _'docker' command is not found!_ 

This error come from the code in _check_docker_status_ function;
_errcode <- system2("command", " -v docker", stdout = FALSE)_

It maybe correctly works with windows;
_errcode <-  system2("WHERE", " docker", stdout = FALSE)_

Thank you for considering.

**Comment by gfinak** [comment]
We've moved the flowjo export to a binary in a docker image, that can be installed from here:
https://hub.docker.com/r/wjiang2/gs-to-flowjo
You'll need to install docker, pull the image, then `gatingset_to_flowjo` will run.
We'll get the documentation for this more front and center, as it was hard to find, apologies for that.

**Comment by jacobpwagner** [comment]
@htanaka1234 , https://github.com/RGLab/CytoML/commit/887039862f335bd3f3705f2b1b185fdc33be2b22 should fix the issue. Please try reinstalling `CytoML` from GitHub to get that commit:
```
devtools::install_github("RGLab/CytoML")
```
